<?php
/**
 * @file friend_block.module
 */

/**
 * Implements hook_block_info()
 */
function friend_block_block_info() {
	$blocks['my_friends'] = array (
		'info' => t('Friends'),
		'cache' => DRUPAL_NO_CACHE,
		'region' => 'sidebar_first',
		'status' => 1,
		'weight' => -5,
	);
	
	return $blocks;
}

/**
 * Implements hook_block_view()
 */
function friend_block_block_view( $block_name ) {
	if ( $block_name=='my_friends' && user_is_logged_in() ) {
		global $user;
		$count = friends_get_friends_count($user->uid);
		if ( $count>0 ) {
			$block['content'] = friend_block_get_friends($user);
			$block['content']['#attached']['css'][] = drupal_get_path('module', 'friend_block').'/friend_block.css';
	    	return $block;	
		}
	}
}

/**
 * The friend block callback.
 */
function friend_block_get_friends( $account=NULL ) {
	if ( !isset($account) ) {
		$account = $GLOBALS['user'];
	}
	
	$uids = friends_get_friends($account->uid);
	if ( !empty($uids) ) {
		$logged_in = db_select('sessions', 's')
		->fields('s', array('uid'))
		->condition('s.uid', $uids, 'IN')
		->execute()
		->fetchCol();
	
		$users = user_load_multiple($uids);
		$online = array();
		$offline = array();		
		foreach($users as $user){
			if( in_array($user->uid, $logged_in) && REQUEST_TIME - $user->access <= variable_get('user_block_seconds_online', 900) ) {  
				$online[$user->uid] = $user;
			} else {
				$offline[$user->uid] = $user;
			}
		}
	
		$output = array();
		foreach( $online as $user ) {
			$output[] = '<div class="user online">' . theme('user_picture', array('account' => $user)) . '</div>';
		} 		
		foreach( $offline as $user ) {
			$output[] = '<div class="user offline">' . theme('user_picture', array('account' => $user)) . '</div>';
		}
		return array(
			'#markup' => implode("\n", $output),
		);
	}
	else {		
		return array('#markup' => t('You have no friend right now.'));
	}
}
